### ISSUE TITLE
Remove "BIDS_Path" and "out_path" from settings.json

### ISSUE THREAD

**Issue by richardkoehler** [neuromodulation/py_neuromodulation#112]
@timonmerk
A feature that I find awkward and that we could think about removing is the "BIDS_Path" and "out_path" parameters from settings.json. 
"settings.json" should in the future be identical for offline analysis (BIDS) and on-line analysis. However, for on-line analysis no BIDS Path is required (or even exists, for that matter). So I would suggest to simply pass BIDS_path as a parameter to the NM_BIDS class in nm_start_BIDS (or simply make it obligatory to pass the BIDS_Path object from mne-bids, then we automatically know the BIDS root (== BIDS_path).
Additionally, the same applies in my opinion to the out_path. I would suggest removing this from the settings.json file and simply passing it to the run object (i.e. NM_BIDS). Because "settings.json" are just general feature settings and should not be specific to my current run. 
Ideally,we should simply be able to copy-paste the settings.json file and apply it to a different project - without having the need to modify the "out_path" parameter inside the file. If one were to forget to modify the "out_path" parameter inside the settings.json file, we would possibly overwrite our previously calculated files.

**Comment by timonmerk** [comment]
@richardkoehler Thanks for mentioning that. I agree that right now the specification doesn't make a lot of sense when calling the toolbox from code.
My idea was that you can specify some "default" parameters like that, and this would allow you calling the run_estimation via command line as well. This is not implemented yet though, and I am not sure if lateron it would become something that might be handy. But I would keep it in mind

**Comment by richardkoehler** [comment]
Okay, then let's leave them in there for now and leave them "optional", i.e. they may be overridden when pyneuromodulation is run from code!
