### ISSUE TITLE
Add Coherence and temporarily remove PDC and DTC

### ISSUE THREAD

**Issue by richardkoehler** [neuromodulation/py_neuromodulation#113]
@timonmerk 
We should maybe think about removing PDC and DTC from main again (and moving them to a branch) until we make sure that they are implemented correctly.
Instead we could think about adding simple coherence, which might be less specific but easier to implement and less computationally expensive.

**Comment by timonmerk** [comment]
Good point! @tsbinns Can you point out which function you use right now?
I would simply use scipy https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.coherence.html

**Comment by tsbinns** [comment]
@timonmerk I'm using [mne.connectivity.spectral_connectivity](https://mne.tools/stable/generated/mne.connectivity.spectral_connectivity.html) in the 'cwt_morlet' mode with 9 cwt cycles.

**Comment by richardkoehler** [comment]
@timonmerk  @tsbinns  For real-time analysis, I think the scipy option would be the way to go right?

**Comment by tsbinns** [comment]
@timonmerk @richardkoehler Computational cost isn't an immediate concern for me, so I haven't compared the two implementations in this regard.
