### ISSUE TITLE
Add cortical-subcortical feature estimation 

### ISSUE THREAD

**Issue by timonmerk** [neuromodulation/py_neuromodulation#13]
Given two channels, calculate: 

 - partial directed coherence 
 - phase amplitude coupling 

Add as separate "feature" file. Needs to implement write to output dataframe

**Comment by timonmerk** [comment]
I would suggest to incorporate this repo for PAC https://github.com/EtienneCmb/tensorpac

For Partial Directed Coherence this looks promising https://gist.github.com/agramfort/9875439

**Comment by timonmerk** [comment]
Thanks a lot for your PR @richardkoehler! We should now evaluate maybe on a single subject level how these features relate to movement. 
Then I would still suggest to have a look at wavelet entropy (https://doi.org/10.1016/S0165-0270(00)00356-3) and PAC implementations (https://doi.org/10.1016/j.clinph.2016.01.015). Maybe those implementations are also nice lab rotation topics :)
But I will also have a look how we can utilize these features.

**Comment by richardkoehler** [comment]
@timonmerk  Yes I will look into how PDC and DTF work with with our current cohorts. I also totally think wavelet entropy and PAC are very promising! However, I won't be able to work on new major features like this for at least the next couple of weeks. But true, those could actually be interesting topics for future lab rotations. In any case we currently already have a large number of features in the toolbox and we can probably already generate so much new material just from these :)

**Comment by timonmerk** [comment]
Prioritize currently on real time capable features, but adding features would be still great addition and use case for py_neuromodulation
