### ISSUE TITLE
Docstring NumPy style

### ISSUE THREAD

**Issue by richardkoehler** [neuromodulation/py_neuromodulation#20]
@timonmerk  
We should probably clean up all docstrings and complete them where they are missing. Should we use NumPy style as a standard for all docstrings? 

Docstring template:

"""
This is the short description of a docstring.

This is the long description ....

Parameters
----------
x : bool
    Description of parameter `x`.
y : list of str
    Description of parameter `y` (with type not specified).

Returns
-------
err_code : int
    Non-zero value indicates error code, or zero on success.

Examples
---------
Example abcde

"""

**Comment by timonmerk** [comment]
That's a good point... I also realized that we have different docstring styles. I think I used the one provided by pylint in vs code. But in general I would vote for adressing the longer docstring version. 

I guess this will also be determined by the sphynx usage lateron when creating the API.

**Comment by timonmerk** [comment]
Closed by current sphinx setup
