### ISSUE TITLE
Fix pre-processing normalization 

### ISSUE THREAD

**Issue by lauraflyra** [neuromodulation/py_neuromodulation#216]
For post-processing normalization, in line 116, when we call the function normalize_and_clip, :

current, previous = _normalize_and_clip(current=current

current is a vector of shape (42,) and if, for example, we want quantile normalization we do:

current = (
    preprocessing.QuantileTransformer(n_quantiles=300)
    .fit(np.nan_to_num(previous))
    .transform(np.expand_dims(current, axis=0))[0, :]
)

np.expand_dims(current, axis=0) -> makes current be in the shape (1,42). 

Now the error in the pre-processing normalization comes from the fact that:

**QuantileTransformer, MinMaxScaler, RobustScaler, and PowerTransformer all expect an input that has dimensions <= 2.**

 

But in line 63 of nm_normalization, inside the normalize_raw function, we call:

current, previous = _normalize_and_clip(current

and in this case the shape of the array given is (1375, 15). Meaning that :

 

np.expand_dims(current, axis=0) -> returns an array of shape (1,1375,15). 

 

So this is exactly why the error happens. 

 

**Why when we call _normalize_and_clip from inside normalize_raw function, do we give it as input an array that is (1375,15), and when we call _normalize_and_clip from inside the normalize_features function, we give it as input an array that is (42,)?**

 

Is the solution simply not using np.expand_dims for the pre-processing normalization case? As in something like this:

if pre-processing:
current = (
    preprocessing.RobustScaler()
    .fit(np.nan_to_num(previous))
    .transform(current)[0, :]
)

**Comment by timonmerk** [comment]
@lauraflyra you did not work on this issue right? Otherwise I would try to fix it now
