### ISSUE TITLE
Adopt the usage of an argument parser (argparse)

### ISSUE THREAD

**Issue by mousa-saeed** [neuromodulation/py_neuromodulation#26]
argparse is a python package that allows for in command line options, arguments and sub-commands

documentation: 
https://docs.python.org/3/library/argparse.html

**Comment by timonmerk** [comment]
@mousa-saeed  thinking about this more it seems now pretty difficult to replace the settings in argv command line arguments. The most usefuly option I see is simply to pass the run file to test_features.py 
test_features.py should be also a module in py_neuromodulation/pyneuromodulation and not just in the examples. It is just difficult to come up with a name.. maybe start_feature_analysis.py is reasonable.

**Comment by mousa-saeed** [comment]
you are correct, it would be difficult to replace all the settings. I think we should only add it extra to give the option to overwrite some settings while having all the default settings in settings.json file, which is for a more deeper control.
if we think about it, after adjusting the settings.json or using it as a default, some specific settings such as the path for the subject needs to be changed, this could be solved with the argparser instead of having to change the settings.json everytime.
how about  feature_extraction.py as a name?

![argparse_adoptation](https://user-images.githubusercontent.com/7423431/113410265-4fab7d80-93b3-11eb-825e-39021a5c466f.PNG)

**Comment by timonmerk** [comment]
@mousa-saeed  Can you make a separate branch and create a pull request? In such way we would see how we can use argparse. 
Currently the main argument will be the run file, since this is not specified in the settings. So simply gettings the run with sys.argv[1] would be also an option

**Comment by mousa-saeed** [comment]
@timonmerk , can you point me to the followings:

- The script that gets called from the command line
- The script that reads settings['BIDS_PATH']

**Comment by timonmerk** [comment]
Hey @mousa-saeed, have a look at settings.py, which reads settings.json. 
Here we append the path to the toolbox everytime with 
`sys.path.append(r'C:\Users\ICN_admin\Documents\py_neuromodulation\pyneuromodulation')`, which would be optimal to fix, maybe we can add it in the settings.json? 

But lateron, if py_neuromodulation get's installed we somehow have the path where it was installed. I need to read about it... 

Currently there is no pressing need to call scripts from the command line. The scripts in example.py should be iteratively called either by wrappers that call them for multiple runs, or call separat features / run_analysis.p files for ML analysis.

**Comment by mousa-saeed** [comment]
@timonmerk , i made a small fix for that in the example_ML.py under the RelativePath branch.
I had to reset the relative path twice, once for the scrip to import other scripts (sys.path.append) and the other one for the script to be able to read the files with os.chdir.

we could avoid having to do this by placing all the example scripts and example runs outside, so we dont have to navigate to parent dirs.

**Comment by timonmerk** [comment]
Can you make a pull request?
