### ISSUE TITLE
Replace "ECOG" column in M1.tsv with "type"

### ISSUE THREAD

**Issue by richardkoehler** [neuromodulation/py_neuromodulation#29]
I would suggest replacing the ECOG column with something like "type" and then specifying the type expicitly, e.g. "ecog", "dbs", "eeg", etc. 
This would give us much more flexibility in the future. Also, "subcortex" channels in the rereferencing function are inferred implicitly by picking channels that are "used"==1 but not "ECOG"==1. By having the actual channel type we could specify subcortex channels explicitly, by e.g. picking channels with the type "dbs"==1.

@timonmerk  what do you think?

**Comment by timonmerk** [comment]
Agree, makes sense
