### ISSUE TITLE
Handle input in multiple data formats 

### ISSUE THREAD

**Issue by toni-neurosc** [neuromodulation/py_neuromodulation#304]
Currently offline data analysis accepts NumPy arrays and Pandas dataframes as input. We can leverage the MNE package to accept a variety of data formats. See https://mne.tools/dev/generated/mne.io.read_raw.html

**Comment by timonmerk** [comment]
Great point @toni-neurosc! We could add a separate function to 
https://github.com/neuromodulation/py_neuromodulation/blob/fd2b112f9647e7160cbae8f8b2e1b09f7f627018/py_neuromodulation/nm_IO.py#L49

and maybe call it `read_raw_mne` and add it to `nm_IO`. Additionally it would be great to add a test maybe `test_mne_raw_io` that utilizes the brainvision file `py_neuromodulation/data/sub-testsub/ses-EphysMedOff/ieeg/sub-testsub_ses-EphysMedOff_task-gripforce_run-0_ieeg.vhdr`.

**Comment by timonmerk** [comment]
Fixed by #329
