### ISSUE TITLE
ECoG decoding example

### ISSUE THREAD

**Issue by alessiaca** [neuromodulation/py_neuromodulation#353]
Hey py_neuromodulation team, 

I just went through the "ECoG Movement decoding example" and noticed that in the text you write "**Here, we show an example using the XGBOOST classifier."**
In the example code however, you use a linear regression model. 
**model = linear_model.LinearRegression()**
 It would be great for new useres if this would be consistent (for me personally it would be nice to have the example with XGBOOST because that is the one I want to use). Thank you very much in advance :)

**Comment by timonmerk** [comment]
Thanks a lot for comment @alessiaca!
