### ISSUE TITLE
Outdated `llvmlite` preventing CI from running on main

### ISSUE THREAD

**Issue by tsbinns** [neuromodulation/py_neuromodulation#367]
CI tests on main branch are attempting to install `llvmlite` v0.36 which has a pinned Python dependency <= 3.10. Not sure if this is a gh action caching issue; the same isn't happening e.g. here: https://github.com/neuromodulation/py_neuromodulation/actions/runs/11033411954/job/30644510625?pr=364#step:5:63

Is it worth adding `llvmlite` to test dependencies and pinning to a more recent version, or would people prefer to wait until the other branches where this isn't occurring are merged into main?

**Comment by timonmerk** [comment]
Thanks for pointing out! I added now `llvmlite` directly as a dependency. I infrrf got an installation error under windows. The [tests](https://github.com/neuromodulation/py_neuromodulation/actions/runs/11144552830/job/30972080071) pass now also
