### ISSUE TITLE
Add column "status" to M1.tsv

### ISSUE THREAD

**Issue by richardkoehler** [neuromodulation/py_neuromodulation#78]
@timonmerk 
I suggest that we add the column "status" (like in BIDS channels.tsv files) to the M1.tsv file values would be "good" or "bad" 
I recently encountered the problem that I wanted to exclude an ECOG channel from the ECOG average reference because it was too noisy, but there is no way to do this, except to hard-code. Alternatively, we could in theory also implement excluding channels by setting the **type** of the bad channel to "bad". This is not 100% logical but this would avoid for us to change the current API. However, the more sustainable and "BIDS-friendly" solution would be to implement the "status" column.
I could easily imagine such a scenario: 

- We want to make real-time predictions from an ECOG grid (e.g. 6 * 5 electrodes), but to reduce computational cost we only want to select the best performing ECOG channel. However, we would like to re-reference this ECOG channel to an average ECOG reference. So the solution would be to mark all ECOG channels as type "ecog", mark the bad ECOG channels as "bad", the others as "good", and only set "used" to 1 for the best performing ECOG channel.

**Comment by timonmerk** [comment]
Hey @richardkoehler, what is the problem if you set "used" to 0 for this channel? In case "used" is 0 we would probably also not want to use this channel for rereferencing right?

**Comment by richardkoehler** [comment]
That would work in some cases, but not always.. because what if you would like to not use a channel for feature estimation (used=0), but still use it for rereferencing (used=1)? The only current solution would be to change the channel type from "ecog" to something else (e.g. "bad")

**Comment by timonmerk** [comment]
Maybe we can simply copy this from the BIDS data? 
Otherwise we would assume that all channels are ok
