### ISSUE TITLE
Add possibility to "create" new channels

### ISSUE THREAD

**Issue by richardkoehler** [neuromodulation/py_neuromodulation#86]
Add the option in "settings.json" to "create" new channels by summation (e.g. new_channel: LFP_R_234, sum_channels: [LFP_R_2, LFP_R_3, LFP_R_4].
Not an imminent priority, but would be nice to have.

**Comment by timonmerk** [comment]
Is still a relevant point for you @richardkoehler? If so I could also work on that point.

**Comment by richardkoehler** [comment]
@timonmerk  Yes, I would say definitely still relevant. Maybe we can work on this next week.

**Comment by timonmerk** [comment]
@richardkoehler For my analysis it did not come into a priority so far, in case you think it will be useful, please feel free to add it
